#!/bin/bash
root="$(cd $(dirname $(realpath ${BASH_SOURCE})) && pwd)"
cd "$root"

user=${SUDO_USER:-$(whoami)}
home=$(eval echo ~$user)

usage(){
    cat<<-EOF
	Usage: $(basename $0) CMD
	CMD:
	    start
	    stop
	    status
	    config
	    em
	EOF
    exit 1
}

start(){
    #tmux new-session -d -s "ssr local" python ROOT/local.py -c ROOT/config-local.json
    case $(uname) in
        Linux)
            #TODO
            echo
            ;;
        Darwin)
            launchctl load -w $home/Library/LaunchAgents/ssrlocal.plist
            ;;
    esac
}

stop(){
    #tmux kill-session -t "ssr local"
    case $(uname) in
        Linux)
            #TODO
            echo
            ;;
        Darwin)
            launchctl unload -w $home/Library/LaunchAgents/ssrlocal.plist
            ;;
    esac
}

config(){
    editor=vi
    if command -v vim >/dev/null 2>&1;then
        editor=vim
    fi
    if [ ! -e $root/config-local.json ];then
        cp $root/config-local.json.example $root/config-local.json
    fi
    $editor $root/config-local.json
    #TODO restart if needed
}

editMyself(){
    editor=vi
    if command -v vim >/dev/null 2>&1;then
        editor=vim
    fi
    $editor $root/ssrlocal
}

status(){
    echo
}

cmd=$1

case $cmd in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
    config)
        config
        ;;
    em)
        editMyself
        ;;
    *)
        usage
        ;;
esac
